### ISSUE TITLE
How to update bitwarden_rs to a newer version?

### ISSUE THREAD

**Issue by garryRsapp1234** [dinger1986/bitwardenrs_install_script#1]
Hi there,

This is more of a question, not an issue. I am new to Github and scripts, and learning my way up. Apologies if this sounds like a dumb question.

Let's say if I install bitwarden_rs using your script. What happens when dani-garcia releases an update to their bitwarden_rs repo. Do I simply download your update.sh and run it or do we have to do something else? 

Cheers,

**Comment by dinger1986** [comment]
Hello,

No problems at all!

If there’s a new version then running update.sh will sort out the upgrade for you. All the script does is automate install or update using the source from bitwarden_rs.

regards,
Daniel




Daniel Lamb

Technical Director

[cid:logo_2094e808-adcc-455a-a5fd-54265dc137fa.jpg]<http://www.flonix.co.uk/>

Flonix Limited
Willowview
Redgorton
Perth
PH1 3EL

Phone: 01738 500400

http://www.flonix.co.uk

Company Reg: SC341802

[cid:fb_11c7c55d-b85e-4b3e-b8d8-daabbed1905e.png]<https://www.facebook.com/Flonixltd/>





________________________________

**Comment by garryRsapp1234** [comment]
Thanks Daniel,

Your script has made it so much easier to install bitwarden_rs on Ubuntu 20.04. Keep up the good work :)
