### ISSUE TITLE
ssh port blocked?

### ISSUE THREAD

**Issue by suricloud** [dinger1986/bitwardenrs_install_script#10]
Before installing bitwarden, i had changed my ssh port and enabeld ssh key,rebooted and installed bitwarden.
Now after reboot the vps, i cant login to my vps?
Is there a firewall or something that is blocking?

**Comment by dinger1986** [comment]
the script automatically opens port 22, 443 and 80 and closes all others, it does say it and asks if you want to continue, by changing the port fail2ban probably wont work either.

Alot of these are basic support or knowledge things that you could find by looking on the internet

**Comment by suricloud** [comment]
what i can i do now? Should i reinstall over again?
I never leave port number to 22.
Possible to edit the port number?

**Comment by dinger1986** [comment]
I would reinstall

yes you can change the script

Currently it says sudo ufw allow OpenSSH change this to sudo ufw allow portnumber/tcp

**Comment by suricloud** [comment]
Hi,

I reinstalled and left port 22 as it is.
I do get this in the end of the installation,is it normal?

./install.sh: line 542: /etc/fail2ban/filter.d/bitwardenrs.conf: Permission deni                                                                                                 ed
./install.sh: line 557: /etc/fail2ban/jail.d/bitwardenrs.local: Permission denie                                                                                                 d
./install.sh: line 569: /etc/fail2ban/filter.d/bitwardenrs-admin.conf: Permissio                                                                                                 n denied
./install.sh: line 584: /etc/fail2ban/jail.d/bitwardenrs-admin.local: Permission                                                                                                  denied

**Comment by dinger1986** [comment]
sorry was a bit missing in the install script, its sorted now

Run this code in terminal to get fail2ban working

#####Fail2ban setup
sudo apt install -y fail2ban

#Create files
sudo touch /etc/fail2ban/filter.d/bitwardenrs.conf
sudo touch /etc/fail2ban/jail.d/bitwardenrs.local
sudo touch /etc/fail2ban/filter.d/bitwardenrs-admin.conf
sudo touch /etc/fail2ban/jail.d/bitwardenrs-admin.local

#Set BitWarden fail2ban filter conf File
bitwardenfail2banfilter="$(cat << EOF
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <HOST>\. Username:.*$
ignoreregex =
EOF
)"
sudo echo "${bitwardenfail2banfilter}" > /etc/fail2ban/filter.d/bitwardenrs.conf

#Set BitWarden fail2ban jail conf File
bitwardenfail2banjail="$(cat << EOF
[bitwardenrs]
enabled = true
port = 80,443,8081
filter = bitwarden
action = iptables-allports[name=bitwarden]
logpath = /var/log/bitwardenrs/error.log
maxretry = 3
bantime = 14400
findtime = 14400
EOF
)"
sudo echo "${bitwardenfail2banjail}" > /etc/fail2ban/jail.d/bitwardenrs.local

#Set BitWarden fail2ban admin filter conf File
bitwardenfail2banadminfilter="$(cat << EOF
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Unauthorized Error: Invalid admin token\. IP: <HOST>.*$
ignoreregex =
EOF
)"
sudo echo "${bitwardenfail2banadminfilter}" > /etc/fail2ban/filter.d/bitwardenrs-admin.conf

#Set BitWarden fail2ban admin jail conf File
bitwardenfail2banadminjail="$(cat << EOF
[bitwardenrs-admin]
enabled = true
port = 80,443
filter = bitwarden-admin
action = iptables-allports[name=bitwarden]
logpath = /var/log/bitwardenrs/error.log
maxretry = 5
bantime = 14400
findtime = 14400
EOF
)"
sudo echo "${bitwardenfail2banadminjail}" > /etc/fail2ban/jail.d/bitwardenrs-admin.local

sudo systemctl restart fail2ban

**Comment by suricloud** [comment]
Ok,
And lets say if i change my ssh before installing bitwarden.
During installation of bitwarden if  choose the option2 for customize installation,do you get the option to enter your ssh port i use so that fail2ban can pick that up ? Or ssh port should stay on 22 ?

**Comment by dinger1986** [comment]
there is no customization of the installation, port 22 is fixed as ssh port
