### ISSUE TITLE
Bitwarden_rs has changed name and repo to "Vaultwarden"

### ISSUE THREAD

**Issue by Octofoxy** [dinger1986/bitwardenrs_install_script#13]
Bitwarden_rs has changed name to Vaultwarden. Installation with the script fails, maybe because of this name change.

**Comment by dinger1986** [comment]
Thanks, I have made the changes now (I think) please feel free to test it and report back, I dont have time at the moment to test it myself.

**Comment by suricloud** [comment]
I was going to open een issue.
For the last 2 days i tried to install on different vps.And i do get this error again and again.

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by dinger1986** [comment]
Please try since the name has been changed.

Like I said before I don't use bitwarden anymore so I am just keeping this going without spending too much time on it

**Comment by suricloud** [comment]
i just updated with the updated script.but still same 502 Bad Gateway

**Comment by suricloud** [comment]
i can try to reinstall fresh again.i will let you know

**Comment by suricloud** [comment]
I installed all fresh again,but the same error:
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by dinger1986** [comment]
Ok I don't know what's wrong with it.

I'll delete this repository as don't have time to fix it

**Comment by suricloud** [comment]
that will be very sad for such a great script you created :(
please dont delete,if you get time you can what is going wrong

**Comment by dinger1986** [comment]
I dont have time or any interest to fix it
