### ISSUE TITLE
Fail if sudo fails 

### ISSUE THREAD

**Issue by nicolas-graves** [dinger1986/bitwardenrs_install_script#15]
Hi ! 
Thanks for your work on this nice and useful script. 

When trying to update, I forgot my bitwardenrs user password, tried to exit, and the script made some mess in my folders. 

Nothing too serious, I guess,  but it would be nice to add a "quit on sudo fail" on the first sudo prompt. 

Thanks again !

**Comment by dinger1986** [comment]
Surely you have your password saved in a your vault?  If you dont have one can recommend vaultwarden ;)

fair point, added to script now.
