### ISSUE TITLE
${HOME}

### ISSUE THREAD

**Issue by schoubi** [dinger1986/bitwardenrs_install_script#17]
Hi, thanks for this script which work well :)

A little bug : 
https://github.com/dinger1986/bitwardenrs_install_script/blob/2d3790165b6cb98dabbcccf083be69092d44ff84/install.sh#L65

should be

`${HOME}/.cargo/env`

As the home of vaulwarden user can be outside /home/

Cheers,

**Comment by dinger1986** [comment]
Of course, can change that now! 

thanks
