### ISSUE TITLE
update script broke installation

### ISSUE THREAD

**Issue by suricloud** [dinger1986/bitwardenrs_install_script#23]
Hi,

With then recent update of the update.sh on ubuntu 22.04 it broke the working vaultwarden.
After update i get this now: 
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

Can acces to vaultwarden anymore.

**Comment by dinger1986** [comment]
Like I have said before countless times, I don't use this.

I don't know why it's broken but suggest you check if everything is downloaded ok. Maybe run it again. Or restore the backup
