### ISSUE TITLE
bitwarden fails to start or panics

### ISSUE THREAD

**Issue by parampavar** [dinger1986/bitwardenrs_install_script#3]
I have tried the script on completely clean Ubuntu install (erase entire disk) twice. 
Both the times the install completes, but navigating to https://bitwarden.DOMAIN.com/admin
 throws a 502 (Bad Gateway)

Digging a bit into the bitwardenrs log, I am seeing that there is an error shown below.

**Please help**

`bitwardenrs@svrz801-ubn:~$ tail -n 60 /var/log/bitwardenrs/error.log 

[2020-12-03 22:48:48.324][ws][INFO] Listening for new connections on 127.0.0.1:3012.
[2020-12-03 22:48:48.324][start][INFO] Rocket has launched from http://127.0.0.1:8000
[2020-12-03 22:48:48.358][panic][ERROR] thread 'unnamed' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }': /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/thread/mod.rs:610
   0: bitwarden_rs::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:483:5
   5: core::panicking::panic_fmt
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/core/src/panicking.rs:85:14
   6: core::option::expect_none_failed
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/core/src/option.rs:1237:5
   7: std::thread::spawn
   8: hyper::server::listener::ListenerPool<A>::accept
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/sys/unix/thread.rs:87:17
  12: start_thread
  13: clone

[2020-12-03 22:48:48.358][panic][ERROR] thread 'main' panicked at 'internal error: entered unreachable code: the call to `handle_threads` should block on success': /home/bitwardenrs/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/1010f6a/core/lib/src/rocket.rs:737
   0: bitwarden_rs::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:483:5
   5: std::panicking::begin_panic_fmt
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:437:5
   6: rocket::rocket::Rocket::launch
   7: bitwarden_rs::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:381:40
      std::panicking::try
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panicking.rs:345:19
      std::panic::catch_unwind
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/panic.rs:382:14
      std::rt::lang_start_internal
             at /rustc/adef9da30f1ecbfeb81312d01ed94ac53f7161ba/library/std/src/rt.rs:51:25
  11: main
  12: __libc_start_main
  13: _start

`

**Comment by seanvandermolen** [comment]
I just had this issue too.  I had to bump the memory to 2G because part of the install around node fails because it runs out of memory.

**Comment by parampavar** [comment]
> I just had this issue too. I had to bump the memory to 2G because part of the install around node fails because it runs out of memory.

I am glad, that you have found the reason for this error.
Please share the steps to increase the memory, and does this require the script to be modified and run on a clean machine again.

**Comment by dinger1986** [comment]
I'll test this over the weekend and modify the script if needed.

**Comment by parampavar** [comment]
> I'll test this over the weekend and modify the script if needed.

Keep up the great work. This script is awesome as it is.

**Comment by dinger1986** [comment]
@parampavar how much ram are you using? is it on an ssd? Just so I can hopefully replicate my end.

**Comment by parampavar** [comment]
My system is prolly an overkill, I plan to add more things to it
![2020-12-04_09-24](https://user-images.githubusercontent.com/4603820/101194371-c5285c80-3612-11eb-9bb1-abb3b65629fb.png)

**Comment by dinger1986** [comment]
Haha wow! Just a bit. I'll check on a machine of similar spec and see what comes up

**Comment by dinger1986** [comment]
Closest I could get is 32gb and its working fine, strange, 
@seanvandermolen I presume you had the issue due to the only running with 1gb? 
@parampavar were you running a VM on that hardware?

**Comment by seanvandermolen** [comment]
@dinger1986 
Yes, the issue occurred when I was running 1GB when it happened, below was the output of the installer.  I might have saved the actual logged that's referenced if you like.

The only other thing I did differently after upgrading to 2GB was to cancel the auto updates at the end of the 20.04 install process.  On the first try with the failed install I let that complete.  Possible that could be an issue as well.

Thanks for the script btw. I've been wanting to switch to Bitwarden all year.

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1409d59]
Security context: 0x0cb008c808d1 <JSObject>
    1: /* anonymous */ [0x17799a9b3cd9] [/home/tp-admin/web/node_modules/acorn/dist/acorn.js:~2945] [pc=0x10386d2fd58a](this=0x0e806d521239 <_class map = 0x85c24ba48d9>)
    2: /* anonymous */ [0x17799a9b2519] [/home/tp-admin/web/node_modules/acorn/dist/acorn.js:809] [bytecode=0x19798bc36131 offset=13](this=0x0e806d521239 <_class map = 0x85c24ba48d9>,0x17fae4ec01...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa18150 node::Abort() [node]
 2: 0xa1855c node::OnFatalError(char const*, char const*) [node]
 3: 0xb965be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb96939 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd53bb5  [node]
 6: 0xd54246 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd60b05 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd619b5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd6446c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd2ae8b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x106d45e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x1409d59  [node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.17.1 build:prod: `gulp prebuild && cross-env NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.17.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dinger1986** [comment]
Probably is the ram (what type of hard drive do you have? I have only tested with SSDs), the build is quite intensive. Have also removed the generation of the db certificate and everything worked fine for me, makes the script run a little faster.

**Comment by seanvandermolen** [comment]
All SSD.  I didn't mind the cert part, but if it's not needed faster is always better!  I have an MS Hype converged setup running Server 2019 DC HV as the hypervisor.

**Comment by dinger1986** [comment]
It's all ssds I have tested on with 1GB ram, haven't tried on hyperv as avoid MS shit as much as possible! 

Think @parampavar issue was that they are running 64GB ram but I'm starting to wonder if it's a VM on it. 

Thanks for your help, pretty sure it's cracked. I'll maybe raise the requirements to 2GB to be safe

**Comment by parampavar** [comment]
@dinger1986 I am not running a VM on this machine.
The main hard drive is nvme (1TB) and I have a secondary SSD (2TB) (only for data)
Hope this helps.

**Comment by dinger1986** [comment]
Sorry not really, I tried it on a 32GB ram machine and it worked fine. Would you not be better running vms or docker containers on that machine?

**Comment by parampavar** [comment]
I went with the docker route, but had challenges with nginx (I am a noob), and I was so excited when I saw your script putting together everything (including the admin token generation and prompting it to be stored to access it)

**Comment by parampavar** [comment]
Is it too difficult to create a script for the docker version?

**Comment by dinger1986** [comment]
Docker seems to be the suggested way to go by bitwarden_rs but not a massive user of docker to be honest which is why I wrote the script, I'm more a VM man.

From Bitwarden_RS GitHub

https://github.com/dani-garcia/bitwarden_rs

docker pull bitwardenrs/server:latest
docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 bitwardenrs/server:latest

https://hub.docker.com/r/bitwardenrs/server

**Comment by parampavar** [comment]
Using docker, I got up to having bitwarden_rs running on localhost, but after that adding reverse_proxy and making it available as public available was bit challenging for me. I think it is mainly due to me not knowing nginx.

**Comment by dinger1986** [comment]
Ok. If nginx is a problem then I suggest VMs.

VMware esxi is free

Proxmox is opensource

Virtual box works on Ubuntu well.

Install one of the above, install Ubuntu 20.04 and then run this script and it should work. 

Configure it with 1cpu and 2gb ram 60gb hdd and bridged network. 

I'll close this now I think but feel free to open another if you need help installing on a VM
