### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by muzicman0** [dinger1986/bitwardenrs_install_script#4]
brand new install (on VM) of Ubuntu 20.04.  Where would I begin to troubleshoot why this isn't working?

Once the script finishes, I get no response on my domain.

**Comment by dinger1986** [comment]
Hello,

Ok so where I would start:

Is it onprem? If so have you opened all the necessary ports?

Is nginx installed? Check the status using systemctl nginx status

Is anything showing up in /var/www/html?

Can you ping the IP?

Did you use a real domain for it?

Let me know about them and let's see.

Daniel

**Comment by muzicman0** [comment]
I use Caddy as a reverse proxy, so anything that comes in on port 443 through my domain get's forwarded to the internal address of the Ubuntu VM.

in /var/www/html, there was the index file (with Debian in the filename).

It appears that let's encrypt is failing, but in my case (because I use Caddy), that shouldn't matter.  I already have valid certs for my sub domain.

yes, I can ping the internal IP (10.3.0.45)

It is a google domain set up as a forwarder to my external IP address, and it is correct.

I have a docker image running BitwardenRS already that works fine, but I am having some management issues with it, and was looking to move to some other way of hosting.

**Comment by dinger1986** [comment]
lets encrypt is integrate into the script so unless the certs are there it wont work.

You probably can copy in the certs manually but I dont know if you would want to do that or if it would indeed work with caddy (i have no knowledge of caddy)
