### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by suricloud** [dinger1986/bitwardenrs_install_script#5]
Hi,
I cant install it on my vps with 20.04?
I tried twice,but i do get these errors?
What is going wrong ?

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.18.0 build:prod: `gulp prebuild && cross-env NODE_ENV=p                                                                                                 roduction webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.18.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitwardenrs/.npm/_logs/2021-02-18T05_20_41_340Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.18.0 dist: `npm run build:prod && gulp postdist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.18.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitwardenrs/.npm/_logs/2021-02-18T05_20_41_371Z-debug.log
[sudo] password for bitwardenrs:
cp: cannot stat '/home/bitwardenrs/bitwarden_rs/target/release/bitwarden_rs': No                                                                                                  such file or directory
mv: cannot stat '/home/bitwardenrs/web/build': No such file or directory
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Created symlink /etc/systemd/system/multi-user.target.wants/bitwarden.service →                                                                                                  /etc/systemd/system/bitwarden.service.

**Comment by dinger1986** [comment]
what does  /home/bitwardenrs/.npm/_logs/2021-02-18T05_20_41_340Z-debug.log have?

Daniel

**Comment by suricloud** [comment]
i formatted the vps and tried again,but no succes :(
can i email you?

**Comment by dinger1986** [comment]
just redact any private info and upload the log please.

**Comment by suricloud** [comment]
Ok will reinstall again, and send the log files.

**Comment by dinger1986** [comment]
thanks, I imagine it will be an error that needs reported to bitwardenrs but I will try and help here first

**Comment by suricloud** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@6.14.11
3 info using node@v12.20.2
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle bitwarden-web@2.18.0~predist: bitwarden-web@2.18.0
6 info lifecycle bitwarden-web@2.18.0~dist: bitwarden-web@2.18.0
7 verbose lifecycle bitwarden-web@2.18.0~dist: unsafe-perm in lifecycle true
8 verbose lifecycle bitwarden-web@2.18.0~dist: PATH: /usr/lib/node_modules/npm/>
9 verbose lifecycle bitwarden-web@2.18.0~dist: CWD: /home/bitwardenrs/web
10 silly lifecycle bitwarden-web@2.18.0~dist: Args: [ '-c', 'npm run build:prod>
11 silly lifecycle bitwarden-web@2.18.0~dist: Returned: code: 1  signal: null
12 info lifecycle bitwarden-web@2.18.0~dist: Failed to exec dist script
13 verbose stack Error: bitwarden-web@2.18.0 dist: `npm run build:prod && gulp >
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/nod>
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/nod>
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)

**Comment by suricloud** [comment]
Here during installation,where the errors started.I am installing this on a 1gb vps of oracle cloud.

error: could not compile `diesel`

Caused by:
  process didn't exit successfully: `rustc --crate-name diesel /home/bitwardenrs                                                                                                 /.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.5/src/lib.rs --error                                                                                                 -format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=d                                                                                                 ep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="32-colu                                                                                                 mn-tables"' --cfg 'feature="chrono"' --cfg 'feature="default"' --cfg 'feature="l                                                                                                 ibsqlite3-sys"' --cfg 'feature="r2d2"' --cfg 'feature="sqlite"' --cfg 'feature="                                                                                                 with-deprecated"' -C metadata=88e55873378a57d7 -C extra-filename=-88e55873378a57                                                                                                 d7 --out-dir /home/bitwardenrs/bitwarden_rs/target/release/deps -L dependency=/h                                                                                                 ome/bitwardenrs/bitwarden_rs/target/release/deps --extern byteorder=/home/bitwar                                                                                                 denrs/bitwarden_rs/target/release/deps/libbyteorder-9d205cc1e15edbc7.rmeta --ext                                                                                                 ern chrono=/home/bitwardenrs/bitwarden_rs/target/release/deps/libchrono-acfae50f                                                                                                 c3b617c8.rmeta --extern diesel_derives=/home/bitwardenrs/bitwarden_rs/target/rel                                                                                                 ease/deps/libdiesel_derives-4c3d88a94c3f6f1d.so --extern libsqlite3_sys=/home/bi                                                                                                 twardenrs/bitwarden_rs/target/release/deps/liblibsqlite3_sys-9e677fa6f57087d7.rm                                                                                                 eta --extern r2d2=/home/bitwardenrs/bitwarden_rs/target/release/deps/libr2d2-eee                                                                                                 87a14a6b93641.rmeta --cap-lints allow -L native=/home/bitwardenrs/bitwarden_rs/t                                                                                                 arget/release/build/libsqlite3-sys-aaa1d533e3ee34e3/out` (signal: 9, SIGKILL: ki                                                                                                 ll)
warning: build failed, waiting for other jobs to finish...
error: build failed
Cloning into 'web'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 24934 (delta 32), reused 24 (delta 13), pack-reused 24873
Receiving objects: 100% (24934/24934), 118.18 MiB | 5.52 MiB/s, done.
Resolving deltas: 100% (18266/18266), done.
Your branch is up to date with 'origin/master'.
--2021-02-19 00:13:12--  https://raw.githubusercontent.com/dani-garcia/bw_web_bu                                                                                                 ilds/master/patches/v2.18.1.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.1                                                                                                 33, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.                                                                                                 133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6870 (6.7K) [text/plain]
Saving to: ‘v2.18.1.patch’

v2.18.1.patch       100%[===================>]   6.71K  --.-KB/s    in 0s

2021-02-19 00:13:12 (59.1 MB/s) - ‘v2.18.1.patch’ saved [6870/6870]

error: patch failed: src/app/services/services.module.ts:135
error: src/app/services/services.module.ts: patch does not apply

> bitwarden-web@2.18.0 sub:init /home/bitwardenrs/web
> git submodule update --init --recursive

Submodule 'jslib' (https://github.com/bitwarden/jslib.git) registered for path '                                                                                                 jslib'
Cloning into '/home/bitwardenrs/web/jslib'...
Submodule path 'jslib': checked out '0951424de77fbb61a38616d13d6c67f74ee19775'
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@                                                                                                 1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my                                                                                                  best with it!

> node-sass@4.13.1 install /home/bitwardenrs/web/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.1                                                                                                 3.1/linux-x64-72_binding.node
Download complete
Binary saved to /home/bitwardenrs/web/node_modules/node-sass/vendor/linux-x64-72                                                                                                 /binding.node
Caching binary to /home/bitwardenrs/.npm/node-sass/4.13.1/linux-x64-72_binding.n                                                                                                 ode

> ngx-infinite-scroll@7.0.1 postinstall /home/bitwardenrs/web/node_modules/ngx-i                                                                                                 nfinite-scroll
> opencollective postinstall


                    Thanks for installing ngx-infinite-scroll
                 Please consider donating to our open collective
                        to help us maintain this package.

                            Number of contributors: 0
                               Number of backers: 6
                                Annual budget: $20
                              Current balance: $172

       Donate: https://opencollective.com/ngx-infinite-scroll/donate


> node-sass@4.13.1 postinstall /home/bitwardenrs/web/node_modules/node-sass
> node scripts/build.js

Binary found at /home/bitwardenrs/web/node_modules/node-sass/vendor/linux-x64-72                                                                                                 /binding.node
Testing binary
Binary is fine

> webpack-cli@3.2.1 postinstall /home/bitwardenrs/web/node_modules/webpack-cli
> lightercollective


     *** Thank you for using webpack-cli! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/webpack/donate

                    ***


> bitwarden-web@2.18.0 postinstall /home/bitwardenrs/web
> npm run sub:init


> bitwarden-web@2.18.0 sub:init /home/bitwardenrs/web
> git submodule update --init --recursive

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/web                                                                                                 pack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/wat                                                                                                 chpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/glo                                                                                                 b-watcher/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/cho                                                                                                 kidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )

added 1318 packages from 633 contributors and audited 1523 packages in 64.568s

5 packages are looking for funding
  run `npm fund` for details

found 674 vulnerabilities (659 low, 5 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade                                                                                                  to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and coul                                                                                                 d be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/we                                                                                                 bpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"                                                                                                 })
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/we                                                                                                 bpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"                                                                                                 })
npm WARN @angular/animations@9.1.12 requires a peer of tslib@^1.10.0 but none is                                                                                                  installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@9.2.4 requires a peer of tslib@^1.9.0 but none is installe                                                                                                 d. You must install peer dependencies yourself.
npm WARN @angular/common@9.1.12 requires a peer of tslib@^1.10.0 but none is ins                                                                                                 talled. You must install peer dependencies yourself.
npm WARN @angular/compiler@9.1.12 requires a peer of tslib@^1.10.0 but none is i                                                                                                 nstalled. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@9.1.12 requires a peer of tslib@^1.10.0 but none                                                                                                  is installed. You must install peer dependencies yourself.
npm WARN @angular/core@9.1.12 requires a peer of tslib@^1.10.0 but none is insta                                                                                                 lled. You must install peer dependencies yourself.
npm WARN @angular/forms@9.1.12 requires a peer of tslib@^1.10.0 but none is inst                                                                                                 alled. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@9.1.12 requires a peer of tslib@^1.10.0 but n                                                                                                 one is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@9.1.12 requires a peer of tslib@^1.10                                                                                                 .0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@9.1.12 requires a peer of tslib@^1.10.0 but none is ins                                                                                                 talled. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/common@^8.0.0 but no                                                                                                 ne is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/compiler@^8.0.0 but                                                                                                  none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/core@^8.0.0 but none                                                                                                  is installed. You must install peer dependencies yourself.
npm WARN angulartics2@9.1.0 requires a peer of tslib@^1.10.0 but none is install                                                                                                 ed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is instal                                                                                                 led. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/cho                                                                                                 kidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/glo                                                                                                 b-watcher/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                 1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                 )

+ jquery@3.5.1
+ node-forge@0.10.0
+ webpack-dev-server@3.11.2
added 64 packages from 49 contributors, removed 48 packages, updated 97 packages                                                                                                  and moved 8 packages in 27.269s

15 packages are looking for funding
  run `npm fund` for details

fixed 654 of 674 vulnerabilities in 1523 scanned packages
  10 vulnerabilities required manual review and could not be updated
  7 package updates for 10 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm aud                                                                                                 it` for steps to fix these manually)

> bitwarden-web@2.18.0 dist /home/bitwardenrs/web
> npm run build:prod && gulp postdist


> bitwarden-web@2.18.0 build:prod /home/bitwardenrs/web
> gulp prebuild && cross-env NODE_ENV=production webpack

[00:14:54] Using gulpfile ~/web/gulpfile.js
[00:14:54] Starting 'prebuild'...
[00:14:54] Starting 'clean'...
[00:14:54] Finished 'clean' after 12 ms
[00:14:54] Starting 'webfonts'...
[00:14:55] Finished 'webfonts' after 174 ms
[00:14:55] Finished 'prebuild' after 189 ms
clean-webpack-plugin: /home/bitwardenrs/web/build/* has been removed.
Compiling @angular/animations : module as esm5
Compiling @angular/core : module as esm5
Compiling @angular/animations/browser : module as esm5
Compiling @angular/animations/browser/testing : module as esm5
Compiling @angular/cdk/collections : module as esm5
Compiling @angular/cdk/accordion : module as esm5
Compiling @angular/common : module as esm5
Compiling @angular/cdk/clipboard : module as esm5
Compiling @angular/cdk/platform : module as esm5
Compiling @angular/cdk/bidi : module as esm5
Compiling @angular/cdk/scrolling : module as esm5
Compiling @angular/cdk/drag-drop : module as esm5
Compiling @angular/cdk/layout : module as esm5
Compiling @angular/cdk/portal : module as esm5
Compiling @angular/cdk/keycodes : module as esm5
Compiling @angular/cdk/overlay : module as esm5
Compiling @angular/cdk/observers : module as esm5
Compiling @angular/cdk/a11y : module as esm5
Compiling @angular/cdk/stepper : module as esm5
Compiling @angular/cdk/table : module as esm5
Compiling @angular/cdk/text-field : module as esm5
Compiling @angular/cdk/tree : module as esm5
Compiling @angular/common/http : module as esm5
Compiling @angular/common/http/testing : module as esm5
Compiling @angular/forms : module as esm5
Compiling @angular/platform-browser : module as esm5
Compiling @angular/platform-browser/animations : module as esm5
Compiling @angular/core/testing : module as esm5
Compiling @angular/platform-browser-dynamic : module as esm5
Compiling @angular/platform-browser/testing : module as esm5
Compiling @angular/compiler/testing : module as esm5
Compiling @angular/platform-browser-dynamic/testing : module as esm5
Compiling @angular/common/testing : module as esm5
Compiling @angular/router : module as esm5
Compiling @angular/router/testing : module as esm5
Compiling angular2-toaster : module as esm5
Compiling angulartics2 : module as esm5
Compiling angulartics2/adobeanalytics : module as esm5
Compiling angulartics2/amplitude : module as esm5
Compiling angulartics2/appinsights : module as esm5
Compiling angulartics2/baidu : module as esm5
Compiling angulartics2/clicky : module as esm5
Compiling angulartics2/facebook : module as esm5
Compiling angulartics2/ga : module as esm5
Compiling angulartics2/ga-enhanced-ecom : module as esm5
Compiling angulartics2/gosquared : module as esm5
Compiling angulartics2/gst : module as esm5
Compiling angulartics2/gtm : module as esm5
Compiling angulartics2/hubspot : module as esm5
Compiling angulartics2/ibm-digital-analytics : module as esm5
Compiling angulartics2/intercom : module as esm5
Compiling angulartics2/kissmetrics : module as esm5
Compiling angulartics2/launch : module as esm5
Compiling angulartics2/mixpanel : module as esm5
Compiling angulartics2/piwik : module as esm5
Compiling angulartics2/pyze : module as esm5
Compiling angulartics2/routerlessmodule : module as esm5
Compiling angulartics2/segment : module as esm5
Compiling angulartics2/splunk : module as esm5
Compiling angulartics2/woopra : module as esm5
Compiling ngx-infinite-scroll : module as esm5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.18.0 build:prod: `gulp prebuild && cross-env NODE_ENV=p                                                                                                 roduction webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.18.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitwardenrs/.npm/_logs/2021-02-19T02_35_46_760Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitwarden-web@2.18.0 dist: `npm run build:prod && gulp postdist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitwarden-web@2.18.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitwardenrs/.npm/_logs/2021-02-19T02_35_46_805Z-debug.log
[sudo] password for bitwardenrs:
Sorry, try again.
[sudo] password for bitwardenrs:
cp: cannot stat '/home/bitwardenrs/bitwarden_rs/target/release/bitwarden_rs': No                                                                                                  such file or directory
mv: cannot stat '/home/bitwardenrs/web/build': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/bitwarden.service →                                                                                                  /etc/systemd/system/bitwarden.service.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-xkit ubuntu-drivers-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-pyinotify whois
Suggested packages:
  mailx monit sqlite3 python-pyinotify-doc
The following NEW packages will be installed:
  fail2ban python3-pyinotify whois
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 444 kB of archives.
After this operation, 2400 kB of additional disk space will be used.
Get:1 http://iad-ad-3.clouds.archive.ubuntu.com/ubuntu focal/universe amd64 fail                                                                                                 2ban all 0.11.1-1 [375 kB]
Get:2 http://iad-ad-3.clouds.archive.ubuntu.com/ubuntu focal/main amd64 python3-                                                                                                 pyinotify all 0.9.6-1.2ubuntu1 [24.8 kB]
Get:3 http://iad-ad-3.clouds.archive.ubuntu.com/ubuntu focal/main amd64 whois am                                                                                                 d64 5.5.6 [44.7 kB]
Fetched 444 kB in 0s (3391 kB/s)
Selecting previously unselected package fail2ban.
(Reading database ... 116423 files and directories currently installed.)
Preparing to unpack .../fail2ban_0.11.1-1_all.deb ...
Unpacking fail2ban (0.11.1-1) ...
Selecting previously unselected package python3-pyinotify.
Preparing to unpack .../python3-pyinotify_0.9.6-1.2ubuntu1_all.deb ...
Unpacking python3-pyinotify (0.9.6-1.2ubuntu1) ...
Selecting previously unselected package whois.
Preparing to unpack .../archives/whois_5.5.6_amd64.deb ...
Unpacking whois (5.5.6) ...
Setting up whois (5.5.6) ...
Setting up fail2ban (0.11.1-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/fail2ban.service → /                                                                                                 lib/systemd/system/fail2ban.service.
Setting up python3-pyinotify (0.9.6-1.2ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.4) ...
Please go to admin url: https://bw.mydomain.com/admin

**Comment by dinger1986** [comment]
How strange, let me test it on a machine, I always use Vultr for VPS and works fine. I'll test it tonight. I ran the upgrade script the other day and worked fine for me which is essentially the same thing.

**Comment by suricloud** [comment]
ok, i tried several times,and also on another vps.
But it fails :( I dont know i do something wrong then?
Hopefully you can get the mistake.

**Comment by dinger1986** [comment]
yeah shall see and get back to you!

**Comment by dinger1986** [comment]
replicated the problem, it appears it needs 2GB ram now for compiling, otherwise npm runs out of memory and crashes. I would suggest trying that and seeing how it goes. I have also changed the requirements on the readme

**Comment by suricloud** [comment]
Oh ok,
I had tested also on 1.5 gb ram vps.there it failed to.
Ok then will try on a 2gb am vps and let you know.

**Comment by dinger1986** [comment]
Yeah I ran too whilst compiling and it used 1.9GB so think 2GB is the minimum now.

What a pain!

**Comment by suricloud** [comment]
I just installed on a 2gb vps,and yes it installed :)
how to run update?
I see there is a webupdate availabe?

**Comment by dinger1986** [comment]
What version does it say it's on?
Daniel

**Comment by suricloud** [comment]
Version
Server Installed Ok
1.19.0-5b146080
Server Latest
1.19.0-5b146080
Web Installed Update
2.18.0
Web Latest
2.18.1d

**Comment by dinger1986** [comment]
ill have a look into this and see why the script isn't picking up 2.18.1d as the newest version

**Comment by suricloud** [comment]
Ok,

Please let me know,because want to install today on my working vps .
Also mention the update command,like when there is a new update,we easy can update the version.

Next thing how to make backups and restore in case my vps crashed?

**Comment by dinger1986** [comment]
Yes you can update when theres a new version using the update script.

I haven't implemented backups in the script, best to check bitwarden_rs for this.

**Comment by suricloud** [comment]
Ok, would be nice if you can implement a backup option to make backups on google driv/onedrive/dropbox.
And a way easily restore.

**Comment by dinger1986** [comment]
its not a priority to me at the moment, you can open a feature request and I can look into this

**Comment by suricloud** [comment]
Ok sure.

**Comment by suricloud** [comment]
What is the update script / commands to get the latest update?

**Comment by dinger1986** [comment]
check the main page, I have added this now, be aware update only updates to 2.18.0 as well at the moment, I am thinking this will need to be brought up with bitwarden_rs but will do some more digging

**Comment by dinger1986** [comment]
I have got in touch via the forum to see what they suggest.

I will report back if/when there is a fix for this, if theres no fix I will close this.

**Comment by suricloud** [comment]
Ok no problem,
How to enable TOTP on my account?
Or does Bitwarden rs version not have totp?

**Comment by dinger1986** [comment]
I would suggest asking on Bitwarden RS forums https://bitwardenrs.discourse.group/ as thats a usability question

**Comment by dinger1986** [comment]
no fix offered by bitwardenrs forums
