### ISSUE TITLE
Let's encrypt renewals fail

### ISSUE THREAD

**Issue by seanvandermolen** [dinger1986/bitwardenrs_install_script#7]
In the version of the script I used, an include to support renewals starts @ line 65

However, the include file is not called in any of the running configs.

On Line 412 There is a setup for SSL that has a duplicate acme-challenge config however the root directory is /acme instead of /letsencrypt like the original include so renewals fail.

On this topic as a requested feature for the installer.  Would be cool to setup a CRON task for let's encrypt.

**Comment by dinger1986** [comment]
Let me look into this, I think I have fixed this on the install script but obviously previous scripts wont have been updated, I should release a patch for this actually. 

The current script makes the cron task work as well.

**Comment by dinger1986** [comment]
Fix implemented in update script
https://raw.githubusercontent.com/dinger1986/bitwardenrs_install_script/master/update.sh
