### ISSUE TITLE
install on 1gb ram oracle cloud

### ISSUE THREAD

**Issue by suricloud** [dinger1986/bitwardenrs_install_script#8]
Hi,can yoy look into this?
Maybe this way we can install on a 1gb ram cloud vps?

https://andtheysay.medium.com/how-i-setup-bitwarden-on-oracle-cloud-free-tier-with-cloudflare-b882579eab80

**Comment by dinger1986** [comment]
if you use precompiled or docker you should be fine, mine is just for installing and compiling from source.

**Comment by suricloud** [comment]
yes but as we see before it fails on 1 gb ram vps.The script require 2gb ram.
I realy want to install on the free oracle cloud vps to make a good use of it :)

**Comment by dinger1986** [comment]
thats fine, feel free to fork the install script and sort it so it will work with less ram, I have made as I was installing a server so shared it however we have abandoned use in our organisation so I will not be further developing this, I will make fixes if there are issues but will not be making improvements.

**Comment by suricloud** [comment]
Maybe you can make precompiled version for 1gb ram vps?

**Comment by dinger1986** [comment]
if you look at bitwardenrs they already have precompiled versions, I didnt want to use that as I would rather compile myself, they also have docker and guides on how to install with docker

**Comment by axlroden** [comment]
Just add a 2gb swap to the instance for installation.
    sudo fallocate -l 2G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo sysctl vm.swappiness=10

And to make it permanent on boot:
    echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
    echo "vm.swappiness=10" /etc/sysctl.conf
 
If you just wanna remove it once install is done:
    sudo swapoff -v /swapfile
    sudo rm /swapfile

That said though, there are some issues with ufw not being installed by standard in oracles ubuntu 20.04 image. 
And some echo to file commands fail with sudo.

**Comment by suricloud** [comment]
> Just add a 2gb swap to the instance for installation.
> sudo fallocate -l 2G /swapfile
> sudo chmod 600 /swapfile
> sudo mkswap /swapfile
> sudo swapon /swapfile
> sudo sysctl vm.swappiness=10
> 
> And to make it permanent on boot:
> echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
> echo "vm.swappiness=10" /etc/sysctl.conf
> 
> If you just wanna remove it once install is done:
> sudo swapoff -v /swapfile
> sudo rm /swapfile
> 
> That said though, there are some issues with ufw not being installed by standard in oracles ubuntu 20.04 image.
> And some echo to file commands fail with sudo.

Ok thanks for sharing it,will try on  my oralce vps
the ufw thing i know, you have to open the ports before installing.

What are the solution for the  echo command that fails with sudo ?

**Comment by axlroden** [comment]
I did it manually via root ..

**Comment by suricloud** [comment]
so you mean the install script fails ?

**Comment by axlroden** [comment]
yeah it cant get permission with your sudo echo > cmds
